services:
  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-root
        IMAGE_TAG: preview
    environment:
      - RUNTIME=develop
      - ENVIRONMENT_NAME=develop
      - CONFIG=config.Develop
      - DEBUG=true
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - COOKIE_DOMAIN=localhost
      - CSP_STYLE_SRC='self',fonts.googleapis.com,p.typekit.net,use.typekit.net
      - CSP_FONT_SRC='self',fonts.gstatic.com,use.typekit.net
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
    env_file:
      - path: .env
        required: false
    ports:
      - 65517:8080
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 65502:8080

  dev:
    environment:
      - CONFIG=config.Test
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
    image: ghcr.io/nationalarchives/tna-python-dev:preview
    volumes:
      - ./:/app

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 65518:8000

  redis:
    image: redis:latest
    volumes:
      - redis:/data

volumes:
  redis:
