services:
  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-root
        IMAGE_TAG: preview
    environment:
      - RUNTIME=develop
      - CONFIG=config.Develop
      - DEBUG=true
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - COOKIE_DOMAIN=localhost
      - CSP_STYLE_SRC='self',fonts.googleapis.com,p.typekit.net,use.typekit.net
      - CSP_FONT_SRC='self',fonts.gstatic.com,use.typekit.net
    env_file:
      - .env
    ports:
      - 65517:8080
    volumes:
      - ./:/app

  dev:
    image: ghcr.io/nationalarchives/tna-python-dev:preview
    volumes:
      - ./:/app

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 65518:8000
