name: Run Playwright tests

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/jod
    - name: Get installed Playwright version
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)")" >> $GITHUB_ENV
      shell: bash
    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
    - name: Install test dependencies
      run: npm ci
      shell: bash
    - run: npx playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
    - run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
    - name: Install system dependencies for WebKit
      # Some WebKit dependencies seem to lay outside the cache and will need to be installed separately
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps webkit
      shell: bash
    - name: Start service
      run: docker compose up --detach --wait app
      shell: bash
    - name: Run tests
      run: CI=true npx playwright test --grep-invert "@wip"
      shell: bash
